### ISSUE TITLE
WSO2-GReg-5.4.0: Carbon management console search page does not get displayed

### ISSUE THREAD

**Issue by saranki** [wso2/product-greg#906]
**Description:**
In the latest wum updated pack of wso2greg-5.4.0 the search page in carbon management console is not displayed. 
![image](https://user-images.githubusercontent.com/20519000/89698669-1021b400-d940-11ea-9787-b0e9b8164a77.png)

But the page is getting displayed in the wso2greg-5.4.0 vanilla pack.
![image](https://user-images.githubusercontent.com/20519000/89698739-642c9880-d940-11ea-8c02-da80af7a76bc.png)

**Affected Product Version:**
wso2greg-5.4.0 latest wum pack(wso2greg-5.4.0+1592926620091)
 
**Steps to reproduce:**
1. Login to the carbon management console
2. In the Main menu --> Resources --> Search the search UI is not displayed.

**Comment by rmsamitha** [comment]
Fixed in wso2greg-5.4.0 wum and already fixed in latest repo.
