### ISSUE TITLE
[Greg-5.4.0]-Store doesn't show "ownedBy" Association

### ISSUE THREAD

**Issue by saranki** [wso2/product-greg#907]
**Description:**
In wso2greg-5.4.0 2 custom assets were created as MDA and E-service. The associations between these assets are as follows.

- eservice ownedBy mda
- eservice usedBy mda

These associations are correctly displayed in the publisher portal and carbon management console. But in the store portal (if customized to display associations is implemented) the "ownedBy" association is not getting displayed. 

This is because only the "usedBy '' association of e-service is returned in the response as the dependencies and the "ownedBy '' association is not returned in the store portal's REST API's response. But the relevant dependencies were retrieved in the publisher REST API call. The relevant publisher and store responses are as follows.

**Publisher**
`"isContentType": false, "associationsTypes": [ { "key": "ownedBy", "value": "fw-store" }, { "key": "usedBy", "value": "fw-store" } ], "associations": { "results": [ { "uniqueAttributesValues": [ "e-service-001-2792" ], "uniqueAttributesNames": [ "overview_code" ], "text": "E-service-1", "type": "application/vnd.wso2-eservice+xml", "associationType": "ownedBy", "uuid": "49a8887a-d875-48e8-b4e1-abe0947fae79", "shortName": "eservice" }, { "uniqueAttributesValues": [ "e-service-002-7926" ], "uniqueAttributesNames": [ "overview_code" ], "text": "E-service-2", "type": "application/vnd.wso2-eservice+xml", "associationType": "usedBy", "uuid": "96b25dd7-2728-486c-8785-03363d3e8410", "shortName": "eservice" } ] }`

**Store**
`{ "id": "8556c591-9806-42a7-81bd-23b0ba1aeceb", "type": "mda", "path": "/_system/governance/mdas/mda-del-001-2313", "lifecycle": "ServiceLifeCycle", "lifecycleState": "Development", "currentLCStateDuration": "228d:08h:40m:25s", "currentLCStateDurationColour": null, "mediaType": "application/vnd.wso2-mda+xml", "attributes": { "overview_code": "mda-del-001-2313", "asaProducer_serviceDefinition": "Delivers the products", "integrations_participation": "Integrates the flow.", "dashboards_url": "http://www.google.com", "overview_name": "MDA-Delivery", "asaProducer_serviceType": "External", "dashboards_description": "Displays the delivery metrics", "integrations_integration": "Integrator-1", "dashboards_dashboard": "Delivery dashboard", "asaConsumer_serviceName": "Packaging", "asaProducer_serviceName": "Delivery", "asaProducer_serviceDescription": "This service is to deliver the products", "overview_description": "This is for delivery purposes.", "asaConsumer_serviceDefinition": "Packing process is handled in this.", "asaConsumer_serviceProvider": "Partner-1" }, "content": { }, "name": "MDA-Delivery", "thumbnail": "", "banner": "", "rating": 0.0, "version": "", "createdDate": "", "_default": false, "nameToChar": "M", "uniqueColor": "#c0392b", "singularLabel": "MDA", "icon": "fw fw-resource", "dependencies": [ ], "dependents": [ { "associationName": "E-service-2", "associationType": "eservice", "associationUUID": "96b25dd7-2728-486c-8785-03363d3e8410", "associationVersion": "eservices" } ], "avgRating": 0.0, "count": 0.0, "ratingPx": 0.0, "isSubscribed": false, "versions": [ ], "isDefault": false, "hasMultipleVersions": false, "dependencyCheck": { "isDependencies": false, "isDependents": true, "isAnyDependence": true } }`

**Affected Product Version:**
wso2greg-5.4.0

**Steps to reproduce:**
1. Create asset RXTs in the carbon management console for MDA and E-service
2. Add the association details in the **< Greg-Home>/repository/conf/governance.xml** file as shown below.
`<Association type="eservice">`
           `<ownedBy reverseAssociation ="owns" iconClass="fw-user">mda</ownedBy>`
            `<usedBy reverseAssociation ="depends" iconClass="fw-globe">mda</usedBy>`
`</Association>`
`<Association type="mda">`
            `<usedBy reverseAssociation ="depends" iconClass="fw-globe">eservice</usedBy>`
`</Association>`
3. Re-start the server
4. Create an MDA and 2 E-services assets in publisher portal
5. In the MDA asset's association tab serach for "usedBy" and add one of the E-services assets. Search for "ownedBy" and add the next E-service asset.
6. In the **repository/deployment/server/jaggeryapps/store/extensions/app/greg-store-defaults/themes/store/partials/asset-attributes.hbs** add `{{dump .}}` at the very first line. This will provide the store response including the dependents and dependencies details.
7. This response will not have the "ownedBy" details.

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/product-greg/pull/908
